spring:
  application:
    name: edu-user
  profiles:
    active: local  # 默认使用 local 环境
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
      config:
        server-addr: ${nacos.server-addr}
        file-extension: yml
        shared-configs:
          - data-id: common-config.yml
            refresh: true  # 支持动态刷新
        import-check:
          enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
