spring:
  application:
    name: edu-message
  profiles:
    active: local  # 默认使用 local 环境
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
        ip: ${nacos.discovery-ip}
      config:
        import-check:
          enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# SpringDoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
