server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/edu_pay?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

nacos:
  server-addr: nacos:8848

# 支付宝配置（沙箱环境）
alipay:
  app-id: 你的应用ID
  private-key: 你的应用私钥
  public-key: 支付宝公钥
  notify-url: http://你的域名/pay/alipay/notify
  return-url: http://你的域名/pay/alipay/return
