server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/edu_pay?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: dev_password
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 192.168.1.100
      port: 6379
      database: 5

nacos:
  server-addr: 192.168.1.100:8848

alipay:
  app-id: your-app-id
  private-key: your-private-key
  public-key: your-public-key
  notify-url: http://192.168.1.100:8080/pay/callback

