server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/edu_course?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: dev_password
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: admin
    password: admin123
  data:
    redis:
      host: 192.168.1.100
      port: 6379
      database: 1

nacos:
  server-addr: 192.168.1.100:8848

