server:
  port: 8085

spring:
  data:
    redis:
      host: 192.168.1.100
      port: 6379
      database: 4

nacos:
  server-addr: 192.168.1.100:8848

elasticsearch:
  uris: http://192.168.1.100:9200

