server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/edu_video?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: dev_password
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 192.168.1.100
      port: 6379
      database: 3

nacos:
  server-addr: 192.168.1.100:8848

minio:
  endpoint: http://192.168.1.100:9000
  access-key: minioadmin
  secret-key: minioadmin123

