spring:
  application:
    name: edu-video
  profiles:
    active: local  # 默认使用 local 环境
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
      config:
        import-check:
          enabled: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# MinIO 配置
minio:
  endpoint: ${minio.endpoint}
  access-key: ${minio.access-key}
  secret-key: ${minio.secret-key}
  bucket-name: edu-video
